BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'rpc://'
BROKER_POOL_LIMIT = 8

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TIMEZONE = 'Asia/Kolkata'
CELERY_ENABLE_UTC = True
